import { AiCapability } from "./types";

export const aiCapabilities: AiCapability[] = [
  // 1. Keamanan & Akses
  {
    id: "01",
    code: "FACE_RECOG",
    name: "Face Recognition",
    nameId: "Pengenalan Wajah & VIP",
    desc: "Real-time face matching against watchlists, blacklists, and VIP lists.",
    descId: "Pencocokan wajah seketika untuk daftar tamu VIP, karyawan, hingga daftar blacklist keamanan.",
    category: "security",
    iconName: "ScanFace",
    featured: true,
  },
  {
    id: "02",
    code: "RE_ID",
    name: "Person Re-Identification",
    nameId: "Pelacakan Lintas Kamera",
    desc: "Tracks individuals across cameras without relying on facial biometrics.",
    descId: "Melacak pergerakan seseorang dari satu kamera ke kamera lain berdasarkan atribut fisik pakaian.",
    category: "security",
    iconName: "UserCheck",
  },
  {
    id: "03",
    code: "INTRUSION",
    name: "Intrusion Detection",
    nameId: "Deteksi Penyusup Area Terlarang",
    desc: "Automatic alerts when restricted areas are entered outside operating hours.",
    descId: "Peringatan otomatis saat ada orang melintasi zona sensitif di luar jam operasional.",
    category: "security",
    iconName: "ShieldAlert",
    featured: true,
  },
  {
    id: "04",
    code: "PERIMETER",
    name: "Perimeter Breach Alert",
    nameId: "Peringatan Pelanggaran Batas",
    desc: "Detects breaches of fence lines or virtual security boundaries.",
    descId: "Mendeteksi penerobosan batas pagar fisik maupun garis virtual keamanan secara presisi.",
    category: "security",
    iconName: "Maximize",
  },
  {
    id: "05",
    code: "TAILGATING",
    name: "Anti-Passback / Tailgating",
    nameId: "Deteksi Akses Ganda / Ekoran",
    desc: "Detects more than one person passing an access point on a single authorization.",
    descId: "Mencegah lebih dari satu orang masuk melalui pintu akses dengan satu kartu akses tap.",
    category: "security",
    iconName: "DoorClosed",
  },
  {
    id: "06",
    code: "WEAPON",
    name: "Weapon Detection",
    nameId: "Deteksi Senjata Tajam / Api",
    desc: "Visual detection of weapon-like objects in public entry checkpoints.",
    descId: "Identifikasi visual instan objek berbahaya di pintu masuk untuk respons cepat aparat.",
    category: "security",
    iconName: "Crosshair",
  },

  // 2. K3 & Keselamatan Kerja
  {
    id: "07",
    code: "PPE_DETECT",
    name: "PPE Compliance",
    nameId: "Kepatuhan APD (K3)",
    desc: "Checks for helmets, vests, masks, and gloves in work areas.",
    descId: "Audit visual otomatis pemakaian helm keselamatan, rompi reflektif, sepatu, dan sarung tangan kerja.",
    category: "safety",
    iconName: "HardHat",
    featured: true,
  },
  {
    id: "08",
    code: "FIRE_SMOKE",
    name: "Fire & Smoke Detection",
    nameId: "Deteksi Asap & Kobaran Api",
    desc: "Early detection of fire and smoke from visual feed, no added sensors.",
    descId: "Deteksi visual dini asap dan lidah api sebelum sensor panas atau sprinkler aktif.",
    category: "safety",
    iconName: "Flame",
    featured: true,
  },
  {
    id: "09",
    code: "FALL_DETECT",
    name: "Fall Detection",
    nameId: "Deteksi Pekerja Jatuh",
    desc: "Detects fall incidents in work areas or public facilities.",
    descId: "Notifikasi darurat seketika jika karyawan atau pengunjung terjatuh dan tidak bergerak.",
    category: "safety",
    iconName: "Activity",
  },
  {
    id: "10",
    code: "SMOKING",
    name: "Smoking Detection",
    nameId: "Deteksi Merokok Sembarangan",
    desc: "Detects smoking activity in designated smoke-free areas.",
    descId: "Menangkap aktivitas merokok di area rawan kebakaran seperti gudang, pabrik, dan pom bensin.",
    category: "safety",
    iconName: "CigaretteOff",
  },
  {
    id: "11",
    code: "IDLE_WORKER",
    name: "Idle Worker Detection",
    nameId: "Pemantauan Produktivitas Staff",
    desc: "Identifies inactive workers during operating hours on the production line.",
    descId: "Mengidentifikasi kekosongan stasiun kerja atau ketidakaktifan di jalur perakitan pabrik.",
    category: "safety",
    iconName: "TimerReset",
  },
  {
    id: "12",
    code: "ABANDONED",
    name: "Abandoned Object",
    nameId: "Deteksi Benda Mencurigakan",
    desc: "Alerts when an object is left unattended in a sensitive area.",
    descId: "Mendeteksi barang atau koper yang ditinggal tanpa pemilik di area publik dan transportasi.",
    category: "safety",
    iconName: "PackageX",
  },

  // 3. Komersial & Analitik Ritel
  {
    id: "13",
    code: "PEOPLE_COUNT",
    name: "People Counting",
    nameId: "Hitung Lalu Lintas Pengunjung",
    desc: "Counts visitor traffic entering and leaving per zone.",
    descId: "Menghitung jumlah pengunjung masuk dan keluar secara akurat untuk konversi penjualan toko.",
    category: "business",
    iconName: "UserPlus",
    featured: true,
  },
  {
    id: "14",
    code: "HEATMAP",
    name: "Heatmap & Dwell Time",
    nameId: "Peta Panas & Durasi Kunjungan",
    desc: "Visualizes busy zones and visitor dwell time per area.",
    descId: "Menganalisis lorong belanja mana yang paling sering dikunjungi dan berapa lama pelanggan berhenti.",
    category: "business",
    iconName: "MapPin",
    featured: true,
  },
  {
    id: "15",
    code: "QUEUE_MGMT",
    name: "Queue Length Monitoring",
    nameId: "Pemantauan Antrean Kasir",
    desc: "Measures queue length to help optimize customer service.",
    descId: "Mengukur panjang antrean kasir atau teller secara otomatis agar segera membuka loket tambahan.",
    category: "business",
    iconName: "Footprints",
  },
  {
    id: "16",
    code: "CROWD_DENSITY",
    name: "Crowd Density",
    nameId: "Kepadatan Kerumunan",
    desc: "Real-time estimate of people count and density in public areas.",
    descId: "Memonitor tingkat kepadatan massa di aula, stasiun, atau mal untuk mencegah penumpukan.",
    category: "business",
    iconName: "Users",
  },
  {
    id: "17",
    code: "LOITERING",
    name: "Loitering Detection",
    nameId: "Deteksi Orang Mondar-Mandir",
    desc: "Flags individuals remaining in one area beyond a reasonable duration.",
    descId: "Menandai individu yang berdiam mencurigakan di sekitar mesin ATM atau batas properti.",
    category: "business",
    iconName: "Clock",
  },
  {
    id: "18",
    code: "VIOLENCE",
    name: "Fight & Violence Detection",
    nameId: "Deteksi Keributan Fisik",
    desc: "Identifies patterns of violent behavior or fighting.",
    descId: "Mengenali gestur perkelahian atau gerakan agresif seketika agar sekuriti segera bertindak.",
    category: "business",
    iconName: "AlertTriangle",
  },

  // 4. Lalu Lintas & Transportasi
  {
    id: "19",
    code: "ANPR_LPR",
    name: "License Plate Recognition",
    nameId: "Pengenalan Plat Nomor (ANPR)",
    desc: "Reads vehicle plates for access control and enforcement.",
    descId: "Membaca plat nomor kendaraan secara otomatis untuk gerbang parkir dan pengawasan kendaraan.",
    category: "traffic",
    iconName: "Car",
    featured: true,
  },
  {
    id: "20",
    code: "VEHICLE_CLASS",
    name: "Vehicle Classification",
    nameId: "Klasifikasi Jenis Kendaraan",
    desc: "Classifies and counts vehicles by type.",
    descId: "Mengelompokkan kendaraan menurut motor, mobil pribadi, bus, dan truk angkutan berat.",
    category: "traffic",
    iconName: "Truck",
  },
  {
    id: "21",
    code: "PARKING_SLOT",
    name: "Parking Occupancy",
    nameId: "Ketersediaan Slot Parkir",
    desc: "Real-time monitoring of parking slot availability.",
    descId: "Memantau ketersediaan slot parkir kosong dan terisi secara visual tanpa sensor tanah tambahan.",
    category: "traffic",
    iconName: "CircleParking",
  },
  {
    id: "22",
    code: "SPEED_EST",
    name: "Speed Estimation",
    nameId: "Estimasi Kecepatan Kendaraan",
    desc: "Estimates vehicle speed from existing camera feeds.",
    descId: "Menghitung perkiraan kecepatan laju kendaraan pada jalan kawasan industri atau jalan tol.",
    category: "traffic",
    iconName: "Gauge",
  },
  {
    id: "23",
    code: "WRONG_WAY",
    name: "Wrong-Way Detection",
    nameId: "Deteksi Lawan Arah",
    desc: "Alerts on vehicles traveling against traffic flow.",
    descId: "Peringatan seketika saat ada kendaraan melintas berlawanan dengan arah jalur yang ditentukan.",
    category: "traffic",
    iconName: "Navigation",
  },
  {
    id: "24",
    code: "TRAFFIC_FLOW",
    name: "Traffic Congestion",
    nameId: "Analisis Arus Kemacetan",
    desc: "Analyzes density and congestion patterns per road segment.",
    descId: "Menganalisis volume dan kemacetan jalan untuk optimasi durasi lampu lalu lintas kota cerdas.",
    category: "traffic",
    iconName: "TrendingUp",
  },
];
