import { AiCapability } from "./types";

export const aiCapabilities: AiCapability[] = [
  // 1. Keamanan & Akses
  {
    id: "01",
    slug: "face-recognition",
    code: "FACE_RECOG",
    name: "Face Recognition",
    nameId: "Pengenalan Wajah & VIP",
    desc: "Real-time face matching against watchlists, blacklists, and VIP lists with instant perimeter notification.",
    descId: "Pencocokan wajah seketika untuk daftar tamu VIP, karyawan, hingga daftar blacklist keamanan.",
    category: "security",
    iconName: "ScanFace",
    featured: true,
    image: "/picture/ai_models/face_recog.jpeg",
    detectionBoxes: [
      {
        label: "FACE #01 (VIP_MATCH)",
        confidence: "99.4%",
        top: "14%",
        left: "45%",
        width: "18%",
        height: "26%",
        color: "green",
      },
    ],
    recommendedCameras: "1080p / 4MP, 25-30 FPS, Eye-level mounting (2.0 - 2.5m)",
    useCaseDetails: [
      "Instant turnstile gate release for authorized staff without physical badges",
      "VIP customer arrival notification to customer service tablet",
      "Immediate security alert if a blacklisted individual enters the premises",
    ],
  },
  {
    id: "02",
    slug: "person-reid",
    code: "RE_ID",
    name: "Person Re-Identification",
    nameId: "Pelacakan Lintas Kamera",
    desc: "Tracks individuals across non-overlapping cameras based on visual apparel appearance without facial biometrics.",
    descId: "Melacak pergerakan seseorang dari satu kamera ke kamera lain berdasarkan atribut fisik pakaian.",
    category: "security",
    iconName: "UserCheck",
    featured: true,
    image: "/picture/ai_models/reid.jpeg",
    detectionBoxes: [
      {
        label: "REID #1042 [NAVY_JACKET]",
        confidence: "97.8%",
        top: "18%",
        left: "38%",
        width: "25%",
        height: "68%",
        color: "blue",
      },
    ],
    recommendedCameras: "1080p, 20-30 FPS, Corridor or wide-angle hallway coverage",
    useCaseDetails: [
      "Cross-camera suspect trajectory mapping across large facilities or campuses",
      "Reconstruct movement paths of lost children in shopping malls within seconds",
      "Forensic investigation across multiple camera angles without biometrics",
    ],
  },
  {
    id: "03",
    slug: "intrusion-detection",
    code: "INTRUSION",
    name: "Intrusion Detection",
    nameId: "Deteksi Penyusup Area Terlarang",
    desc: "Automatic real-time alerts when unauthorized persons or objects enter restricted zones outside operating hours.",
    descId: "Peringatan otomatis saat ada orang melintasi zona sensitif di luar jam operasional.",
    category: "security",
    iconName: "ShieldAlert",
    featured: true,
    image: "/picture/ai_models/restricted.jpeg",
    detectionBoxes: [
      {
        label: "ZONE_BREACH: RESTRICTED",
        confidence: "98.9%",
        top: "30%",
        left: "40%",
        width: "28%",
        height: "60%",
        color: "red",
      },
    ],
    recommendedCameras: "1080p / 4MP, IR Night Vision capability, 15-30 FPS",
    useCaseDetails: [
      "Server room and data center unauthorized access detection",
      "After-hours warehouse perimeter and loading dock surveillance",
      "Automated siren trigger and central command center popup",
    ],
  },
  {
    id: "04",
    slug: "perimeter-breach-alert",
    code: "PERIMETER",
    name: "Perimeter Breach Alert",
    nameId: "Peringatan Pelanggaran Batas",
    desc: "Detects breaches of physical fence lines or virtual tripwire security boundaries with high resistance to false alarms.",
    descId: "Mendeteksi penerobosan batas pagar fisik maupun garis virtual keamanan secara presisi.",
    category: "security",
    iconName: "Maximize",
    image: "/picture/ai_models/perimeter.jpeg",
    detectionBoxes: [
      {
        label: "TRIPWIRE_CROSSED",
        confidence: "96.5%",
        top: "30%",
        left: "47%",
        width: "24%",
        height: "58%",
        color: "red",
      },
    ],
    recommendedCameras: "4MP Bullet cameras with IP67 rating, Long IR range",
    useCaseDetails: [
      "Industrial estate boundary fence climbing and cutting alert",
      "Virtual boundary enforcement along critical facility perimeters",
      "Elimination of false triggers from swaying vegetation and small animals",
    ],
  },
  {
    id: "05",
    slug: "tailgating-detection",
    code: "TAILGATING",
    name: "Anti-Passback / Tailgating",
    nameId: "Deteksi Akses Ganda / Ekoran",
    desc: "Detects when more than one person passes through an access point or turnstile on a single credential authorization.",
    descId: "Mencegah lebih dari satu orang masuk melalui pintu akses dengan satu kartu akses tap.",
    category: "security",
    iconName: "DoorClosed",
    image: "/picture/ai_models/tailgating.jpeg",
    detectionBoxes: [
      {
        label: "PERSON #1: AUTH",
        confidence: "99.1%",
        top: "20%",
        left: "40%",
        width: "20%",
        height: "65%",
        color: "green",
      },
      {
        label: "PERSON #2: TAILGATE",
        confidence: "95.4%",
        top: "25%",
        left: "50%",
        width: "22%",
        height: "63%",
        color: "red",
      },
    ],
    recommendedCameras: "1080p, Overhead top-down or 45-degree angle above turnstiles",
    useCaseDetails: [
      "Prevents unauthorized entry behind legitimate employees at secure doorways",
      "Turnstile integration to sound local buzzers on double-entry attempts",
      "Automated incident logging with snapshot and timestamp in the security audit trail",
    ],
  },
  {
    id: "06",
    slug: "weapon-detection",
    code: "WEAPON",
    name: "Weapon Detection",
    nameId: "Deteksi Senjata Tajam / Api",
    desc: "Visual detection of drawn firearms and sharp weapons at checkpoints for ultra-fast proactive threat mitigation.",
    descId: "Identifikasi visual instan objek berbahaya di pintu masuk untuk respons cepat aparat.",
    category: "security",
    iconName: "Crosshair",
    image: "/picture/ai_models/weapon.jpeg",
    detectionBoxes: [
      {
        label: "FIREARM_DETECTED",
        confidence: "94.2%",
        top: "45%",
        left: "52%",
        width: "18%",
        height: "18%",
        color: "red",
      },
    ],
    recommendedCameras: "4MP, high shutter speed, zero motion blur",
    useCaseDetails: [
      "Immediate lockdown protocol activation upon weapon identification",
      "Silent alert dispatch to law enforcement and on-site tactical security",
      "Public transportation hubs and critical infrastructure gatekeeping",
    ],
  },

  // 2. K3 & Keselamatan Kerja
  {
    id: "07",
    slug: "ppe-compliance",
    code: "PPE_DETECT",
    name: "PPE Compliance",
    nameId: "Kepatuhan APD (K3)",
    desc: "Automated real-time auditing of personal protective equipment including hard hats, safety vests, masks, and gloves.",
    descId: "Audit visual otomatis pemakaian helm keselamatan, rompi reflektif, sepatu, dan sarung tangan kerja.",
    category: "safety",
    iconName: "HardHat",
    featured: true,
    image: "/picture/ai_models/ppe.jpeg",
    detectionBoxes: [
      {
        label: "HARD_HAT: OK",
        confidence: "98.7%",
        top: "15%",
        left: "42%",
        width: "16%",
        height: "14%",
        color: "green",
      },
      {
        label: "SAFETY_VEST: MISSING",
        confidence: "96.2%",
        top: "40%",
        left: "38%",
        width: "24%",
        height: "40%",
        color: "red",
      },
    ],
    recommendedCameras: "1080p / 4MP wide view at site entrance and heavy work zones",
    useCaseDetails: [
      "Daily automated compliance scorecards for manufacturing and construction sites",
      "Intercom broadcast notification when a worker enters without mandatory gear",
      "Substantial reduction in workplace safety audit citations and insurance liability",
    ],
  },
  {
    id: "08",
    slug: "fire-smoke-detection",
    code: "FIRE_SMOKE",
    name: "Fire & Smoke Detection",
    nameId: "Deteksi Asap & Kobaran Api",
    desc: "Early optical detection of open flames and rising smoke plumes seconds before physical heat sensors trigger.",
    descId: "Deteksi visual dini asap dan lidah api sebelum sensor panas atau sprinkler aktif.",
    category: "safety",
    iconName: "Flame",
    featured: true,
    image: "/picture/ai_models/fire_smoke.jpeg",
    detectionBoxes: [
      {
        label: "SMOKE_PLUME",
        confidence: "97.3%",
        top: "5%",
        left: "30%",
        width: "35%",
        height: "60%",
        color: "amber",
      },
      {
        label: "FLAME_CORE",
        confidence: "99.0%",
        top: "65%",
        left: "42%",
        width: "20%",
        height: "25%",
        color: "red",
      },
    ],
    recommendedCameras: "High dynamic range (HDR) cameras overlooking wide open spaces",
    useCaseDetails: [
      "High-ceiling warehouses where smoke takes minutes to reach ceiling sensors",
      "Outdoor chemical storage yards, oil depots, and recycling facilities",
      "Instant alarm and push alert with live video snippet to the fire brigade",
    ],
  },
  {
    id: "09",
    slug: "fall-detection",
    code: "FALL_DETECT",
    name: "Fall Detection",
    nameId: "Deteksi Pekerja Jatuh",
    desc: "Immediate alert when a worker collapses or falls from heights and remains stationary, expediting medical response.",
    descId: "Notifikasi darurat seketika jika karyawan atau pengunjung terjatuh dan tidak bergerak.",
    category: "safety",
    iconName: "Activity",
    image: "/picture/ai_models/fall.jpeg",
    detectionBoxes: [
      {
        label: "FALL_INCIDENT_MAN_DOWN",
        confidence: "96.8%",
        top: "50%",
        left: "35%",
        width: "30%",
        height: "25%",
        color: "red",
      },
    ],
    recommendedCameras: "Wide-angle ceiling mounted cameras, 20-30 FPS",
    useCaseDetails: [
      "Lone-worker safety compliance in remote machine rooms or substations",
      "Elderly care facilities and hospital patient recovery corridors",
      "Construction scaffolding and mezzanine fall hazard alerting",
    ],
  },
  {
    id: "10",
    slug: "smoking-detection",
    code: "SMOKING",
    name: "Smoking Detection",
    nameId: "Deteksi Merokok Sembarangan",
    desc: "Flags cigarette and vape smoking gestures in designated fire-hazard or smoke-free corporate premises.",
    descId: "Menangkap aktivitas merokok di area rawan kebakaran seperti gudang, pabrik, dan pom bensin.",
    category: "safety",
    iconName: "CigaretteOff",
    image: "/picture/ai_models/smoking.jpeg",
    detectionBoxes: [
      {
        label: "SMOKING_ACTIVITY",
        confidence: "95.1%",
        top: "40%",
        left: "45%",
        width: "16%",
        height: "20%",
        color: "amber",
      },
    ],
    recommendedCameras: "1080p, 25 FPS, Focus on designated non-smoking stairwells and fuel stations",
    useCaseDetails: [
      "Fuel stations, gas storage, and paint booth explosion risk reduction",
      "Non-smoking stairwell and washroom compliance monitoring",
      "Automated snapshot capture sent directly to safety officer dashboard",
    ],
  },
  {
    id: "11",
    slug: "idle-worker-detection",
    code: "IDLE_WORKER",
    name: "Idle Worker Detection",
    nameId: "Pemantauan Produktivitas Staff",
    desc: "Monitors assembly line stations for operator vacancy or prolonged non-productive inactivity during operating shifts.",
    descId: "Mengidentifikasi kekosongan stasiun kerja atau ketidakaktifan di jalur perakitan pabrik.",
    category: "safety",
    iconName: "TimerReset",
    image: "/picture/ai_models/idle_worker.jpeg",
    detectionBoxes: [
      {
        label: "STATION_04: VACANT >10M",
        confidence: "93.7%",
        top: "27%",
        left: "30%",
        width: "25%",
        height: "45%",
        color: "amber",
      },
    ],
    recommendedCameras: "Fixed focal length camera covering production workstations",
    useCaseDetails: [
      "Identifies bottlenecks and unmanned assembly lines in manufacturing plants",
      "Measures true uptime vs downtime without intrusive wearables",
      "Correlates line stoppages with visual proof for process engineering optimization",
    ],
  },
  {
    id: "12",
    slug: "abandoned-object-detection",
    code: "ABANDONED",
    name: "Abandoned Object",
    nameId: "Deteksi Benda Mencurigakan",
    desc: "Alerts security teams when unattended bags, boxes, or parcels are left stationary in public or sensitive areas.",
    descId: "Mendeteksi barang atau koper yang ditinggal tanpa pemilik di area publik dan transportasi.",
    category: "safety",
    iconName: "PackageX",
    image: "/picture/ai_models/abandoned_object.jpeg",
    detectionBoxes: [
      {
        label: "UNATTENDED_OBJECT >180S",
        confidence: "98.2%",
        top: "55%",
        left: "42%",
        width: "16%",
        height: "18%",
        color: "red",
      },
    ],
    recommendedCameras: "1080p or 4K wide-angle covering public transit lobbies and airports",
    useCaseDetails: [
      "Airport terminal, train station, and government lobby security",
      "Fire exit obstruction monitoring by misplaced boxes or pallets",
      "Early warning for suspicious package protocols",
    ],
  },

  // 3. Komersial & Analitik Ritel
  {
    id: "13",
    slug: "people-counting",
    code: "PEOPLE_COUNT",
    name: "People Counting",
    nameId: "Hitung Lalu Lintas Pengunjung",
    desc: "High-accuracy bidirectional visitor traffic counting per doorway, zone, or floor for retail conversion analytics.",
    descId: "Menghitung jumlah pengunjung masuk dan keluar secara akurat untuk konversi penjualan toko.",
    category: "business",
    iconName: "UserPlus",
    featured: true,
    image: "/picture/ai_models/people_counting.jpeg",
    detectionBoxes: [
      {
        label: "IN: 1,428 | OUT: 1,310",
        confidence: "99.2%",
        top: "25%",
        left: "20%",
        width: "50%",
        height: "65%",
        color: "green",
      },
    ],
    recommendedCameras: "Top-down overhead cameras (2.5m - 4.5m mounting height)",
    useCaseDetails: [
      "Precise store footfall conversion rates calculated against POS sales data",
      "Live building occupancy calculation to satisfy maximum crowd safety limits",
      "Hourly visitor inflow trends to optimize sales staff scheduling",
    ],
  },
  {
    id: "14",
    slug: "heatmap-dwell-time",
    code: "HEATMAP",
    name: "Heatmap & Dwell Time",
    nameId: "Peta Panas & Durasi Kunjungan",
    desc: "Spatial density heatmaps tracking customer dwell duration and traffic flow throughout retail floors and showroom aisles.",
    descId: "Menganalisis lorong belanja mana yang paling sering dikunjungi dan berapa lama pelanggan berhenti.",
    category: "business",
    iconName: "MapPin",
    featured: true,
    image: "/picture/ai_models/heatmap.jpeg",
    detectionBoxes: [
      {
        label: "HIGH_DWELL_ZONE (avg 4m12s)",
        confidence: "96.4%",
        top: "45%",
        left: "10%",
        width: "80%",
        height: "45%",
        color: "amber",
      },
    ],
    recommendedCameras: "Fisheye 360-degree or high-mounted wide-angle lens",
    useCaseDetails: [
      "Determine high-value premium merchandising end-caps and display zones",
      "Optimize store layout to eliminate dead zones and customer friction points",
      "Measure A/B testing impact of new window displays and product promotions",
    ],
  },
  {
    id: "15",
    slug: "queue-length-monitoring",
    code: "QUEUE_MGMT",
    name: "Queue Length Monitoring",
    nameId: "Pemantauan Antrean Kasir",
    desc: "Measures customer queue length and waiting times at checkout counters, triggering alerts when thresholds are crossed.",
    descId: "Mengukur panjang antrean kasir atau teller secara otomatis agar segera membuka loket tambahan.",
    category: "business",
    iconName: "Footprints",
    image: "/picture/ai_models/queue.jpeg",
    detectionBoxes: [
      {
        label: "QUEUE_WAIT: 6 PERSONS (>4 MIN)",
        confidence: "97.5%",
        top: "35%",
        left: "20%",
        width: "69%",
        height: "40%",
        color: "red",
      },
    ],
    recommendedCameras: "Overhead or angled view of checkout counters",
    useCaseDetails: [
      "Automatic dispatch alert to open backup cashier lanes when queue exceeds 4 people",
      "Tracks average service duration per cashier for operational benchmarking",
      "Reduces customer abandonment and walkouts in retail and bank branches",
    ],
  },
  {
    id: "16",
    slug: "crowd-density",
    code: "CROWD_DENSITY",
    name: "Crowd Density",
    nameId: "Kepadatan Kerumunan",
    desc: "Calculates crowd density per square meter in public spaces to proactively prevent stampedes and bottlenecks.",
    descId: "Memonitor tingkat kepadatan massa di aula, stasiun, atau mal untuk mencegah penumpukan.",
    category: "business",
    iconName: "Users",
    image: "/picture/ai_models/crowd.jpeg",
    detectionBoxes: [
      {
        label: "DENSITY_LEVEL: HIGH (3.8 pers/m²)",
        confidence: "95.6%",
        top: "20%",
        left: "15%",
        width: "70%",
        height: "60%",
        color: "red",
      },
    ],
    recommendedCameras: "High-angle or elevated outdoor/indoor surveillance cameras",
    useCaseDetails: [
      "Event venues, stadiums, and concert hall crowd safety management",
      "Train platform congestion warnings for passenger flow regulation",
      "Automated notification to facility managers before critical density thresholds",
    ],
  },
  {
    id: "17",
    slug: "loitering-detection",
    code: "LOITERING",
    name: "Loitering Detection",
    nameId: "Deteksi Orang Mondar-Mandir",
    desc: "Identifies persons remaining stationary or wandering within sensitive zones beyond configurable time thresholds.",
    descId: "Menandai individu yang berdiam mencurigakan di sekitar mesin ATM atau batas properti.",
    category: "business",
    iconName: "Clock",
    image: "/picture/ai_models/loitering.jpeg",
    detectionBoxes: [
      {
        label: "LOITERING_ALERT (DURATION: 5m30s)",
        confidence: "96.1%",
        top: "25%",
        left: "40%",
        width: "22%",
        height: "62%",
        color: "amber",
      },
    ],
    recommendedCameras: "1080p, covering ATM booths, parking lots, and building perimeter",
    useCaseDetails: [
      "ATM vestibule fraud and robbery prevention",
      "Vandalism deterrence around perimeter walls and parking garages",
      "Automated voice warning triggering over PA speakers",
    ],
  },
  {
    id: "18",
    slug: "fight-violence-detection",
    code: "VIOLENCE",
    name: "Fight & Violence Detection",
    nameId: "Deteksi Keributan Fisik",
    desc: "Recognizes rapid physical altercations, aggressive posturing, and fight patterns to dispatch security instantly.",
    descId: "Mengenali gestur perkelahian atau gerakan agresif seketika agar sekuriti segera bertindak.",
    category: "business",
    iconName: "AlertTriangle",
    image: "/picture/ai_models/violence.jpeg",
    detectionBoxes: [
      {
        label: "VIOLENT_ALTERCATION",
        confidence: "94.8%",
        top: "30%",
        left: "32%",
        width: "38%",
        height: "50%",
        color: "red",
      },
    ],
    recommendedCameras: "30 FPS high-frame rate cameras in entertainment and hospitality venues",
    useCaseDetails: [
      "Nightlife venues, bars, and sports arena security monitoring",
      "School campus hallway and courtyard conflict detection",
      "Immediate alert popup on security monitoring wall with live audio chime",
    ],
  },

  // 4. Lalu Lintas & Transportasi
  {
    id: "19",
    slug: "license-plate-recognition",
    code: "ANPR_LPR",
    name: "License Plate Recognition",
    nameId: "Pengenalan Plat Nomor (ANPR)",
    desc: "High-speed automatic license plate character recognition for parking barrier automation and stolen vehicle alerts.",
    descId: "Membaca plat nomor kendaraan secara otomatis untuk gerbang parkir dan pengawasan kendaraan.",
    category: "traffic",
    iconName: "Car",
    featured: true,
    image: "/picture/ai_models/license_plate.jpeg",
    detectionBoxes: [
      {
        label: "PLATE: B 1234 SAM [MATCH]",
        confidence: "99.6%",
        top: "58%",
        left: "40%",
        width: "22%",
        height: "14%",
        color: "green",
      },
      {
        label: "VEHICLE: SEDAN",
        confidence: "98.1%",
        top: "32%",
        left: "25%",
        width: "52%",
        height: "48%",
        color: "blue",
      },
    ],
    recommendedCameras: "Dedicated LPR camera with motorized zoom, IR strobe, and fast shutter",
    useCaseDetails: [
      "Ticketless automated barrier gate entry and exit for registered residents/staff",
      "Stolen or suspect vehicle blacklist alert across tollways and checkpoints",
      "Parking duration billing calculation with timestamped vehicle snapshot",
    ],
  },
  {
    id: "20",
    slug: "vehicle-classification",
    code: "VEHICLE_CLASS",
    name: "Vehicle Classification",
    nameId: "Klasifikasi Jenis Kendaraan",
    desc: "Classifies and tallies vehicles into categories: motorcycles, passenger cars, delivery vans, buses, and heavy trucks.",
    descId: "Mengelompokkan kendaraan menurut motor, mobil pribadi, bus, dan truk angkutan berat.",
    category: "traffic",
    iconName: "Truck",
    image: "/picture/ai_models/vehicle_class.jpeg",
    detectionBoxes: [
      {
        label: "CLASS: HEAVY_TRUCK",
        confidence: "97.4%",
        top: "22%",
        left: "28%",
        width: "46%",
        height: "58%",
        color: "blue",
      },
    ],
    recommendedCameras: "Traffic surveillance camera positioned overlooking roadways",
    useCaseDetails: [
      "Heavy vehicle toll rate categorization and axle count estimation",
      "Restricted road entry enforcement for trucks during peak hours",
      "City infrastructure load modeling and logistics hub vehicle mix reporting",
    ],
  },
  {
    id: "21",
    slug: "parking-occupancy",
    code: "PARKING_SLOT",
    name: "Parking Occupancy",
    nameId: "Ketersediaan Slot Parkir",
    desc: "Monitors open-air and indoor parking bay occupancy visually without requiring expensive individual ultrasonic sensors.",
    descId: "Memantau ketersediaan slot parkir kosong dan terisi secara visual tanpa sensor tanah tambahan.",
    category: "traffic",
    iconName: "CircleParking",
    image: "/picture/ai_models/parking.jpeg",
    detectionBoxes: [
      {
        label: "SLOT_A12: VACANT",
        confidence: "98.3%",
        top: "35%",
        left: "17%",
        width: "28%",
        height: "45%",
        color: "green",
      },
      {
        label: "SLOT_A13: OCCUPIED",
        confidence: "99.1%",
        top: "35%",
        left: "58%",
        width: "28%",
        height: "45%",
        color: "red",
      },
    ],
    recommendedCameras: "Single elevated 4K camera monitoring 30-50 parking spaces simultaneously",
    useCaseDetails: [
      "Cuts hardware costs compared to individual ground sensors by up to 80%",
      "Real-time electronic signage displaying available spots per parking aisle",
      "Mobile app integration guiding drivers directly to empty spaces",
    ],
  },
  {
    id: "22",
    slug: "speed-estimation",
    code: "SPEED_EST",
    name: "Speed Estimation",
    nameId: "Estimasi Kecepatan Kendaraan",
    desc: "Estimates vehicle travel velocity from calibrated video streams to detect speeding violations on premises.",
    descId: "Menghitung perkiraan kecepatan laju kendaraan pada jalan kawasan industri atau jalan tol.",
    category: "traffic",
    iconName: "Gauge",
    image: "/picture/ai_models/speed.jpeg",
    detectionBoxes: [
      {
        label: "SPEED: 58 KM/H (LIMIT: 40)",
        confidence: "93.9%",
        top: "35%",
        left: "30%",
        width: "42%",
        height: "48%",
        color: "red",
      },
    ],
    recommendedCameras: "30-60 FPS camera aligned parallel to road vector",
    useCaseDetails: [
      "Industrial plant internal road speed limit enforcement (e.g. 20-30 km/h limit)",
      "Residential gated community traffic calming",
      "Correlates vehicle license plate with speed violation snapshot",
    ],
  },
  {
    id: "23",
    slug: "wrong-way-detection",
    code: "WRONG_WAY",
    name: "Wrong-Way Detection",
    nameId: "Deteksi Lawan Arah",
    desc: "Detects vehicles or motorcycles traveling counter to the designated one-way traffic direction, preventing head-on collisions.",
    descId: "Peringatan seketika saat ada kendaraan melintas berlawanan dengan arah jalur yang ditentukan.",
    category: "traffic",
    iconName: "Navigation",
    image: "/picture/ai_models/wrong_way.jpeg",
    detectionBoxes: [
      {
        label: "WRONG_WAY_VIOLATION",
        confidence: "97.8%",
        top: "30%",
        left: "35%",
        width: "36%",
        height: "52%",
        color: "red",
      },
    ],
    recommendedCameras: "1080p, fixed view facing one-way ramps or tunnel portals",
    useCaseDetails: [
      "Highway exit ramp wrong-way driver early warning system",
      "Basement parking spiral ramp flow enforcement",
      "Immediate strobe light activation to alert approaching traffic",
    ],
  },
  {
    id: "24",
    slug: "traffic-congestion",
    code: "TRAFFIC_FLOW",
    name: "Traffic Congestion",
    nameId: "Analisis Arus Kemacetan",
    desc: "Measures vehicle queue length, road occupancy percentage, and flow throughput to dynamically control traffic lights.",
    descId: "Menganalisis volume dan kemacetan jalan untuk optimasi durasi lampu lalu lintas kota cerdas.",
    category: "traffic",
    iconName: "TrendingUp",
    image: "/picture/ai_models/traffic_flow.jpeg",
    detectionBoxes: [
      {
        label: "CONGESTION: SEVERE (QUEUE: 180M)",
        confidence: "95.2%",
        top: "20%",
        left: "20%",
        width: "60%",
        height: "65%",
        color: "red",
      },
    ],
    recommendedCameras: "High-mast intersection cameras with wide area view",
    useCaseDetails: [
      "Smart City adaptive traffic signal timer adjustments based on queue length",
      "Automated incident alert when traffic slows to a standstill on expressways",
      "City planning historical traffic density reporting and peak-hour analysis",
    ],
  },
];
